### ISSUE TITLE
Android Light header text not black

### ISSUE THREAD

**Issue by ghost** [01org/appframework#525]
The css generated by the <a href="http://app-framework-software.intel.com/csschooser.php">Css Choser</a> doesn't override the header text color for the h1 tag.

To get around this, I've added the following rule underneath the "#afui.android > #header" rule.

``` css
#afui.android > #header h1 {
    color:inherit;
}
```
